os: linux
language: shell
arch: s390x 

services:
  - docker
  
script:
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker pull quay.io/montana/s390x2
  - docker manifest inspect quay.io/montana/s390x2
  - uname -r 
  
deploy:
  provider: script
  script: 
  - bash build.sh
  
  on:
    branch: master
