language: shell
sudo: required
os: linux

services:
  - docker
  
script:
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker pull quay.io/montana/montana-s390x

deploy:
  provider: script
  script: 
  - bash build.sh
  
  on:
    branch: master
