language: shell
dist: xenial
sudo: required
os: linux

services:
  - docker
  
  
addons:
  apt:
    packages:
      - docker-ce
      
matrix:
  include:
    - env: CONFIG=linux_ppc64le_ UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/montana/ppc64le
      os: linux
      arch: ppc64le


script:
  - docker pull quay.io/montana/ppc64le

deploy:
  provider: script
  script: 
  - bash build.sh
  
  on:
    branch: master
