language: shell
dist: xenial
sudo: required
os: linux
arch: ppc64le

services:
  - docker
  
register: override_template

- name: Reload systemd daemon if template is changed.
  systemd:
    daemon_reload: true
  when: override_template is changed
  

script:
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker pull quay.io/montana/ppc64le

deploy:
  provider: script
  script: 
  - bash build.sh
  
  on:
    branch: master
