language: generic

arch: ppc64le

services:
  - docker

script:
  - docker pull quay.io/montana/ppc64le

deploy:
  provider: script
  script: 
  - chmod u+x build.sh
  
  on:
    branch: master
# trigger
