language: shell
os: linux

services:
  - docker
  
script:
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker pull quay.io/montana/s390x2

deploy:
  provider: script
  script: 
  - bash build.sh
  
  on:
    branch: master
