language: generic

matrix:
  include:
    - env: CONFIG=linux_ppc64le_ UPLOAD_PACKAGES=True PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/montana/ppc64le
      os: linux
      arch: ppc64le


services:
  - docker

script:
  - docker pull quay.io/montana/ppc64le

deploy:
  provider: script
  script: 
  - bash build.sh
  
  on:
    branch: master
