---
dist: jammy
language: shell
services: docker

jobs:
  include:
   - stage: Building ppc64le image
     arch: ppc64le
     script: chmod +x ./build.sh; ./build.sh
   - stage: Building x86_64 image
     arch: amd64
     script: chmod +x ./build.sh; ./build.sh
   - stage: Building multi-arch image
     arch: ppc64le
     script: chmod +x ./create-multi-arch.sh; ./create-multi-arch.sh
   - stage: Run x86_64 image
     arch: amd64
     script: docker pull quay.io/montana/multi-arch:multi-arch-latest; docker run --rm quay.io/montana/multi-arch:multi-arch-latest
   - stage: Run ppc64le image
     arch: ppc64le
     script: docker pull quay.io/montana/multi-arch:multi-arch-latest; docker run --rm quay.io/montana/multi-arch:multi-arch-latest
