language: shell
dist: xenial
sudo: required
os: linux

services:
  - docker
  
script:
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - docker pull quay.io/montana/ppc64le

deploy:
  provider: script
  script: 
  - bash build.sh
  
  on:
    branch: master

#try
